// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUcEDa56MKWDc-8ztKTuzOmRUZqTsNDQ',
    appId: '1:242301906654:web:cab980118a954e6b1b9c4f',
    messagingSenderId: '242301906654',
    projectId: 'iitg-campus-sync',
    authDomain: 'iitg-campus-sync.firebaseapp.com',
    storageBucket: 'iitg-campus-sync.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnmsuVKiNk4_fgN9WaasDMu01vCaem2kg',
    appId: '1:242301906654:android:be45b55d1a26596c1b9c4f',
    messagingSenderId: '242301906654',
    projectId: 'iitg-campus-sync',
    storageBucket: 'iitg-campus-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJAKr5yKHbZ0Cx_ebtOwEYHG4pwwgkn8',
    appId: '1:242301906654:ios:9dcce642613090e41b9c4f',
    messagingSenderId: '242301906654',
    projectId: 'iitg-campus-sync',
    storageBucket: 'iitg-campus-sync.appspot.com',
    iosBundleId: 'com.IitgCampusSync.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJAKr5yKHbZ0Cx_ebtOwEYHG4pwwgkn8',
    appId: '1:242301906654:ios:0444b2c736abbd6c1b9c4f',
    messagingSenderId: '242301906654',
    projectId: 'iitg-campus-sync',
    storageBucket: 'iitg-campus-sync.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUcEDa56MKWDc-8ztKTuzOmRUZqTsNDQ',
    appId: '1:242301906654:web:612f1a69e782cfe31b9c4f',
    messagingSenderId: '242301906654',
    projectId: 'iitg-campus-sync',
    authDomain: 'iitg-campus-sync.firebaseapp.com',
    storageBucket: 'iitg-campus-sync.appspot.com',
  );
}